"""grant change author

Revision ID: 73d534822e97
Revises: aff11fabe8fa
Create Date: 2026-09-21 22:25:50.509265

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73d534822e97"
down_revision: str | Sequence[str] | None = "aff11fabe8fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grant_changes", sa.Column("changed_by", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grant_changes", "changed_by")
    # ### end Alembic commands ###
