"""raw document check tracking

Revision ID: 596663977586
Revises: ac2208d9c7a9
Create Date: 2026-09-21 19:04:54.628865

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "596663977586"
down_revision: str | Sequence[str] | None = "ac2208d9c7a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_documents",
        sa.Column(
            "last_checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("raw_documents", sa.Column("change_key", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_documents", "change_key")
    op.drop_column("raw_documents", "last_checked_at")
    # ### end Alembic commands ###
