"""grant storage: item key, manual overrides, indexes

Revision ID: aff11fabe8fa
Revises: 792defc71023
Create Date: 2026-09-21 21:59:43.821954

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aff11fabe8fa"
down_revision: str | Sequence[str] | None = "792defc71023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extraction_results_raw_document_id"), table_name="extraction_results")
    op.create_index(
        "ix_extraction_results_document_created",
        "extraction_results",
        ["raw_document_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "grant_sources", sa.Column("item_key", sa.Text(), server_default="", nullable=False)
    )
    op.drop_constraint(op.f("uq_grant_sources_source_id_url"), "grant_sources", type_="unique")
    op.create_unique_constraint(
        op.f("uq_grant_sources_source_id_url_item_key"),
        "grant_sources",
        ["source_id", "url", "item_key"],
    )
    op.add_column(
        "grants",
        sa.Column(
            "manual_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.create_index(
        "ix_grants_search",
        "grants",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, "
                "coalesce(title, '') || ' ' || coalesce(description, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_grants_search", table_name="grants", postgresql_using="gin")
    op.drop_column("grants", "manual_overrides")
    op.drop_constraint(
        op.f("uq_grant_sources_source_id_url_item_key"), "grant_sources", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_grant_sources_source_id_url"),
        "grant_sources",
        ["source_id", "url"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("grant_sources", "item_key")
    op.drop_index("ix_extraction_results_document_created", table_name="extraction_results")
    op.create_index(
        op.f("ix_extraction_results_raw_document_id"),
        "extraction_results",
        ["raw_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###
