"""initial schema

Revision ID: ac2208d9c7a9
Revises:
Create Date: 2026-09-21 18:33:57.153010

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac2208d9c7a9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funders",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalised_name", sa.Text(), nullable=False),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column(
            "funder_type",
            sa.Enum(
                "foundation",
                "government",
                "multilateral",
                "corporate",
                "other",
                name="funder_type",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funders")),
    )
    op.create_index(
        op.f("ix_funders_normalised_name"), "funders", ["normalised_name"], unique=False
    )
    op.create_table(
        "grant_types",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["grant_types.id"],
            name=op.f("fk_grant_types_parent_id_grant_types"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_types")),
        sa.UniqueConstraint("slug", name=op.f("uq_grant_types_slug")),
    )
    op.create_table(
        "org_types",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["org_types.id"],
            name=op.f("fk_org_types_parent_id_org_types"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_types")),
        sa.UniqueConstraint("slug", name=op.f("uq_org_types_slug")),
    )
    op.create_table(
        "regions",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["regions.id"],
            name=op.f("fk_regions_parent_id_regions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("slug", name=op.f("uq_regions_slug")),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("adapter", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "html",
                "rss",
                "api",
                "pdf",
                name="source_type",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("schedule", sa.String(length=100), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("terms_reviewed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_sources_name")),
    )
    op.create_table(
        "themes",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["themes.id"],
            name=op.f("fk_themes_parent_id_themes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_themes")),
        sa.UniqueConstraint("slug", name=op.f("uq_themes_slug")),
    )
    op.create_table(
        "grants",
        sa.Column("funder_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("normalised_title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount_min", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("amount_max", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("amount_text", sa.Text(), nullable=True),
        sa.Column("opening_date", sa.Date(), nullable=True),
        sa.Column("closing_date", sa.Date(), nullable=True),
        sa.Column(
            "deadline_type",
            sa.Enum(
                "fixed",
                "rolling",
                "multiple",
                "unknown",
                name="deadline_type",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("deadline_text", sa.Text(), nullable=True),
        sa.Column("eligibility_text", sa.Text(), nullable=True),
        sa.Column("application_url", sa.Text(), nullable=True),
        sa.Column("funder_page_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "upcoming",
                "open",
                "closed",
                "rolling",
                "unknown",
                name="grant_status",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("documents_required", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("funder_priorities", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("contact_url", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["funders.id"],
            name=op.f("fk_grants_funder_id_funders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grants")),
    )
    op.create_index(op.f("ix_grants_closing_date"), "grants", ["closing_date"], unique=False)
    op.create_index(op.f("ix_grants_fingerprint"), "grants", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_grants_funder_id"), "grants", ["funder_id"], unique=False)
    op.create_index(op.f("ix_grants_status"), "grants", ["status"], unique=False)
    op.create_table(
        "raw_documents",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=200), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_documents_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_documents")),
    )
    op.create_index(
        op.f("ix_raw_documents_content_hash"), "raw_documents", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_raw_documents_source_url_fetched",
        "raw_documents",
        ["source_id", "url", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "region_countries",
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_region_countries_region_id_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_region_countries")),
        sa.UniqueConstraint(
            "region_id", "country_code", name=op.f("uq_region_countries_region_id_country_code")
        ),
    )
    op.create_index(
        op.f("ix_region_countries_country_code"), "region_countries", ["country_code"], unique=False
    )
    op.create_table(
        "source_runs",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "partial",
                "failed",
                name="run_status",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column("items_discovered", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_fetched", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_unchanged", sa.Integer(), server_default="0", nullable=False),
        sa.Column("grants_created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("grants_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("errors", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "error_log",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_runs_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_runs")),
    )
    op.create_index(op.f("ix_source_runs_source_id"), "source_runs", ["source_id"], unique=False)
    op.create_table(
        "extraction_results",
        sa.Column("raw_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "llm",
                "rules",
                "api",
                name="extraction_method",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_extraction_results_raw_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_results")),
    )
    op.create_index(
        op.f("ix_extraction_results_raw_document_id"),
        "extraction_results",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "grant_changes",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("source_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "change_source",
            sa.Enum(
                "pipeline",
                "manual",
                name="change_source",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            server_default="pipeline",
            nullable=False,
        ),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column(
            "old_value", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "new_value", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_changes_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["source_runs.id"],
            name=op.f("fk_grant_changes_source_run_id_source_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_changes")),
    )
    op.create_index(op.f("ix_grant_changes_grant_id"), "grant_changes", ["grant_id"], unique=False)
    op.create_table(
        "grant_countries",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_countries_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_countries")),
        sa.UniqueConstraint(
            "grant_id", "country_code", name=op.f("uq_grant_countries_grant_id_country_code")
        ),
    )
    op.create_index(
        op.f("ix_grant_countries_country_code"), "grant_countries", ["country_code"], unique=False
    )
    op.create_table(
        "grant_grant_types",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("grant_type_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_grant_types_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grant_type_id"],
            ["grant_types.id"],
            name=op.f("fk_grant_grant_types_grant_type_id_grant_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_grant_types")),
        sa.UniqueConstraint(
            "grant_id", "grant_type_id", name=op.f("uq_grant_grant_types_grant_id_grant_type_id")
        ),
    )
    op.create_index(
        op.f("ix_grant_grant_types_grant_type_id"),
        "grant_grant_types",
        ["grant_type_id"],
        unique=False,
    )
    op.create_table(
        "grant_org_types",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("org_type_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_org_types_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_type_id"],
            ["org_types.id"],
            name=op.f("fk_grant_org_types_org_type_id_org_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_org_types")),
        sa.UniqueConstraint(
            "grant_id", "org_type_id", name=op.f("uq_grant_org_types_grant_id_org_type_id")
        ),
    )
    op.create_index(
        op.f("ix_grant_org_types_org_type_id"), "grant_org_types", ["org_type_id"], unique=False
    )
    op.create_table(
        "grant_regions",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_regions_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_grant_regions_region_id_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_regions")),
        sa.UniqueConstraint(
            "grant_id", "region_id", name=op.f("uq_grant_regions_grant_id_region_id")
        ),
    )
    op.create_index(
        op.f("ix_grant_regions_region_id"), "grant_regions", ["region_id"], unique=False
    )
    op.create_table(
        "grant_sources",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("raw_document_id", sa.Uuid(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("missing_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_sources_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_grant_sources_raw_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_grant_sources_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_sources")),
        sa.UniqueConstraint("source_id", "url", name=op.f("uq_grant_sources_source_id_url")),
    )
    op.create_index(op.f("ix_grant_sources_grant_id"), "grant_sources", ["grant_id"], unique=False)
    op.create_table(
        "grant_themes",
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_grant_themes_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["themes.id"],
            name=op.f("fk_grant_themes_theme_id_themes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grant_themes")),
        sa.UniqueConstraint("grant_id", "theme_id", name=op.f("uq_grant_themes_grant_id_theme_id")),
    )
    op.create_index(op.f("ix_grant_themes_theme_id"), "grant_themes", ["theme_id"], unique=False)
    op.create_table(
        "review_items",
        sa.Column("grant_id", sa.Uuid(), nullable=True),
        sa.Column("raw_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "low_confidence",
                "missing_required_fields",
                "conflicting_values",
                "possible_duplicate",
                "deadline_changed",
                "possibly_removed",
                "extraction_failed",
                "ambiguous_currency",
                "fetch_failed_repeatedly",
                name="review_reason",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "resolved",
                "dismissed",
                name="review_status",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("resolved_by", sa.String(length=200), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
            name=op.f("fk_review_items_grant_id_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_review_items_raw_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_items")),
    )
    op.create_index(op.f("ix_review_items_grant_id"), "review_items", ["grant_id"], unique=False)
    op.create_index(
        "ix_review_items_status_reason", "review_items", ["status", "reason"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_items_status_reason", table_name="review_items")
    op.drop_index(op.f("ix_review_items_grant_id"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_grant_themes_theme_id"), table_name="grant_themes")
    op.drop_table("grant_themes")
    op.drop_index(op.f("ix_grant_sources_grant_id"), table_name="grant_sources")
    op.drop_table("grant_sources")
    op.drop_index(op.f("ix_grant_regions_region_id"), table_name="grant_regions")
    op.drop_table("grant_regions")
    op.drop_index(op.f("ix_grant_org_types_org_type_id"), table_name="grant_org_types")
    op.drop_table("grant_org_types")
    op.drop_index(op.f("ix_grant_grant_types_grant_type_id"), table_name="grant_grant_types")
    op.drop_table("grant_grant_types")
    op.drop_index(op.f("ix_grant_countries_country_code"), table_name="grant_countries")
    op.drop_table("grant_countries")
    op.drop_index(op.f("ix_grant_changes_grant_id"), table_name="grant_changes")
    op.drop_table("grant_changes")
    op.drop_index(op.f("ix_extraction_results_raw_document_id"), table_name="extraction_results")
    op.drop_table("extraction_results")
    op.drop_index(op.f("ix_source_runs_source_id"), table_name="source_runs")
    op.drop_table("source_runs")
    op.drop_index(op.f("ix_region_countries_country_code"), table_name="region_countries")
    op.drop_table("region_countries")
    op.drop_index("ix_raw_documents_source_url_fetched", table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_content_hash"), table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_index(op.f("ix_grants_status"), table_name="grants")
    op.drop_index(op.f("ix_grants_funder_id"), table_name="grants")
    op.drop_index(op.f("ix_grants_fingerprint"), table_name="grants")
    op.drop_index(op.f("ix_grants_closing_date"), table_name="grants")
    op.drop_table("grants")
    op.drop_table("themes")
    op.drop_table("sources")
    op.drop_table("regions")
    op.drop_table("org_types")
    op.drop_table("grant_types")
    op.drop_index(op.f("ix_funders_normalised_name"), table_name="funders")
    op.drop_table("funders")
    # ### end Alembic commands ###
