"""raw document discovery metadata

Revision ID: 792defc71023
Revises: 596663977586
Create Date: 2026-09-21 20:27:46.242901

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "792defc71023"
down_revision: str | Sequence[str] | None = "596663977586"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_documents",
        sa.Column("discovery_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_documents", "discovery_metadata")
    # ### end Alembic commands ###
